# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.6.0
        hooks:
            -   id: check-yaml
            -   id: check-added-large-files
                args: [ '--maxkb=1024' ]
            -   id: end-of-file-fixer
    -   repo: https://github.com/mxr/unkey
        rev: v0.0.1
        hooks:
            -   id: unkey
    -   repo: https://github.com/MarcoGorelli/auto-walrus
        rev: v0.2.2
        hooks:
            -   id: auto-walrus
    -   repo: https://github.com/jazzband/pip-tools
        rev: 7.4.1
        hooks:
            -   id: pip-compile
                files: pyproject.toml
    -   repo: https://github.com/astral-sh/ruff-pre-commit
        rev: v0.3.5
        hooks:
            -   id: ruff
                args: [ --fix, --exit-zero ]
            -   id: ruff-format
default_language_version:
    python: python3.12
