site_name: marketplace_apis
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      repository: packify-org/marketplace_apis
      branch: main
  #  - optimize
  - mkdocstrings:
      handlers:
        python:
          paths: [ 'marketplace_apis' ]
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: [ "!^_" ]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
  - autorefs
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
#      js_files:
#          - my/javascript/dir/file1.js
#          - my/javascript/dir/file2.js
#      css_files:
#          - my/css/dir/file1.css
#          - my/css/dir/file2.css
repo_url: https://github.com/packify-org/marketplace_apis
repo_name: packify-org/marketplace_apis
edit_uri: edit/main/docs/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  features:
    - content.action.view
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top

markdown_extensions:
  - toc:
      permalink: true
      title: "На этой странице:"
  - tables
  - pymdownx.blocks.admonition
  - pymdownx.blocks.tab:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      auto_title: true
      use_pygments: true
      linenums: true
      guess_lang: true
      default_lang: python
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg



nav:
  - Введение: index.md
  - API:
      - marketplace_apis: reference/
